name: Build and Push Rasenmaeher UI Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_nginx:
    name: Publish NGinx Docker image (${{ matrix.theme }})
    # Disabled: images are published from react-rasenmaeher-ui-v2. TBD how images should be published.
    if: false
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        theme: [default, fdf]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: rasenmaeher-${{ matrix.theme }}
          component: ui
          target: k8s_nginx
          build-args: |
            VITE_THEME=${{ matrix.theme }}
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}

  publish_files:
    name: Publish file delivery Docker image (${{ matrix.theme }})
    # Disabled: images are published from react-rasenmaeher-ui-v2. TBD how images should be published.
    if: false
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        theme: [default, fdf]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: rasenmaeher-ui-${{ matrix.theme }}
          component: worker
          target: production
          build-args: |
            VITE_THEME=${{ matrix.theme }}
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
